#      _   _           _     _____  _             _                #
#     | \ | |         | |   |  __ \| |           (_)               #
#     |  \| | _____  _| |_  | |__) | |_   _  __ _ _ _ __  ___      #
#     | . ` |/ _ \ \/ / __| |  ___/| | | | |/ _` | | '_ \/ __|     #
#     | |\  |  __/>  <| |_  | |    | | |_| | (_| | | | | \__ \     #
#     |_| \_|\___/_/\_\\__| |_|    |_|\__,_|\__, |_|_| |_|___/     #
#                                           __/ |                  #
#                                          |___/                   #
#                       Servidor de Suporte                        #
#                      discord.gg/JtTN7E6A2q                       #

database:
  type: 'sqlite' # Opções válidas: 'sqlite' e 'mysql'
  mysql:
    address: 'localhost:3306'
    username: 'root'
    password: ''
    database: 'test'
  sqlite:
    file: 'database/database.db'

plugin:
  configuration:
    # Sistema de bolsa de valores
    purse:
      enable: true # usar o sistema
      media: 40 # um valor maior que esse significa que a bolsa está em alta
      minValue: 10 # valor mínimo da bolsa
      maxValue: 90 # valor máximo da bolsa
      nextUpdate: 600 # tempo para atualizar em segundos
    # Valor inicial
    # Quando um jogador entra no servidor, começa com essa quantia
    initial-balance: 1000
    # Dinheiro mínimo necessário para enviar a um jogador
    # Evitar flodarem /money pay <jogador> 1
    min-value: 1000000
    # opções válidas: 'DECIMAL' e 'LETTER'
    format-type: 'LETTER' # letter = 1K, 1M etc... decimal = 1.000,00, 1.000.000,00 etc...
    # delay de salvamento das contas online (em segundos)
    save-delay: 300